name: PR Building and SonarQube

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env: 
  SONARQUBE_HOST: http://139.59.242.187:9000
  SONARQUBE_PROJECT_KEY: react-jest
  SONARQUBE_PROJECT_NAME: react-jest
  SONARQUBE_BASE_BRANCH_NAME: ${{ github.base_ref }} 
  SONARQUBE_HEAD_BRANCH_NAME: ${{ github.head_ref }} 
  SONARQUBE_PR_KEY: ${{ github.event.number || github.event.pull_request.number }}
  NODE_VERSION: 18

defaults:
  run:
    shell: bash

jobs:
  pr-build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Run Test Coverage
        run: npm run test:coverage
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
      - name: Run SonarQube Scanner
        run: >-
          sonar-scanner
          -Dsonar.host.url=${{ env.SONARQUBE_HOST }}
          -Dsonar.projectKey=${{ env.SONARQUBE_PROJECT_KEY }}
          -Dsonar.projectName=${{ env.SONARQUBE_PROJECT_NAME }}
          -Dsonar.pullrequest.key=${{ env.SONARQUBE_PR_KEY }}
          -Dsonar.pullrequest.branch=${{ env.SONARQUBE_HEAD_BRANCH_NAME }}
          -Dsonar.pullrequest.base=${{ env.SONARQUBE_BASE_BRANCH_NAME }}
