name: PR Building and SonarQube

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env: 
  SONARQUBE_HOST: http://139.59.242.187:9000
  SONARQUBE_PROJECT_KEY: react-jest
  SONARQUBE_BASE_BRANCH_NAME: ${{ github.base_ref }} 
  SONARQUBE_HEAD_BRANCH_NAME: ${{ github.head_ref }} 
  SONARQUBE_PR_KEY: ${{ github.event.number || github.event.pull_request.number }}
  NODE_VERSION: 18

defaults:
  run:
    shell: bash

jobs:
  check-branch:
    runs-on: [self-hosted]
    name: Check base branch existed on sonarqube
    steps:
      - name:
        id: check-sonarqube
        uses: CPB/check-branch-from-sonarqube@v1
        with:
          sonarqube-host: ${{ env.SONARQUBE_HOST }}
          project-key: ${{ env.SONARQUBE_PR_KEY }}
          branch: ${{ env.SONARQUBE_BASE_BRANCH_NAME }}
    outputs:
      check: ${{ steps.check-sonarqube.outputs.exists }}
  pr-build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Run Test Coverage
        run: npm run test:coverage
